import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Link from "next/link";
import Image from "next/image";
import {
  FiInstagram,
  FiLinkedin,
  FiTwitter,
  FiYoutube,
} from "react-icons/fi";
import { AiFillDiscord } from "react-icons/ai";
import "./globals.css";

import Logo from "@/public/Header/logo-light.png";
import logo from "@/public/Home/logo.png";


const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[#0E0F18] ${montserrat.className}`}>
      <header className="text-white p-3 flex items-center justify-between bg-[#0E0F18] md:mx-10 mx-4">
          <Link href="/" className="flex items-center gap-4">
            <Image src={Logo} alt="Logo" className="h-20 w-20" />
            <h1>Developers & Coders Club</h1>
          </Link>
          <nav className="md:flex items-center gap-10  hidden">
            <Link className="hover:text-gray-200" href="/">
              Home
            </Link>
            <Link href="/events">Events</Link>
            <Link target="_blank" rel="noopener" href="http://cphub.dccnita.in/">CP Hub</Link>
            <Link href="/timeline">Timeline</Link>
            <Link href="/teams">Teams</Link> 
            
          </nav>
        </header>
        {children}
        <footer
          className={`px-[10%] bg-footer-image bg-no-repeat bg-cover pt-20 text-white space-y-8`}
        >
          <div className=" mt-24 flex justify-between">
            <Image
              src={logo}
              alt={"logo"}
              className="w-32 h-32 aspect-auto"
              height={512}
              width={512}
            />
            <div className="flex flex-col space-y-5">
              <Link href="/" title="Home">Home</Link>
              <Link href="/events" title="Events">Events</Link>
              <Link href="/teams" title="Teams">Teams</Link>
            </div>
          </div>
          <div className="flex justify-between w-full py-4 items-center mx-10">
            <div className="space-y-8">
              <h4 className="uppercase font-medium text-2xl">
                Developers & Coders Club NITA
              </h4>
              <p className="font-normal">
                National Institute of Technology, Agartala,
                <br />
                Jirania, Tripura - 799046
              </p>
            </div>
            <div>
              <h4 className="text-2xl uppercase font-medium text-right">
                Social
              </h4>
              <div className="flex items-center justify-around gap-5 py-2">
                <Link href="">
                  <FiTwitter className="aspect-square h-7 w-7" />
                </Link>
                <Link href="">
                  <FiInstagram className="aspect-square h-7 w-7" />
                </Link>
                <Link href="">
                  <FiLinkedin className="aspect-square h-7 w-7" />
                </Link>
                <Link href="">
                  <AiFillDiscord className="aspect-square h-7 w-7" />
                </Link>

                <Link href="">
                  <FiYoutube className="aspect-square h-7 w-7" />
                </Link>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
